server:
  port: 8080

spring:

  application:
    name: portfolio_server
  devtools:
    livereload:
      enabled: true # ?? ??
    restart:
      enabled: true # ???
  thymeleaf:
    cache: false # ?? ??


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portfolio_server
    username: root
    password: 12341234

  jpa:
    hibernate:
      ddl-auto: update

      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    user:
      name: test
      password: 1234
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  web:
    resources:
      static-locations: file:/Users/suhyeon/Documents/pofol/portfolio/

jwt:
  secret: 037c774c547189f75fb74ddcf37545f35b8f5f58000bebf99fd7320d7b2a6c93


fileLocation: /Users/suhyeon/Documents/pofol/portfolio     # 서버 내부에서 사용(파일 저장 경로)
uploadPath: file:/Users/suhyeon/Documents/pofol/portfolio/    # 클라이언트가 파일 접근을 위한 url 경로 사용


logging:
  level:
    org:
      hibernate:
        type:
          description:
            sql: trace